version: "3"
services:
    prediction_api:
        build: .
        container_name: "inference_container"
        ports:
            - "8000:8000"
        platform: "linux/arm64" # Specify the platform for M1 Mac